version: "3.7"
services:
  streamlit-server:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../data:/app/data
      - ../web:/app/web
